baseURL = "https://pinnitone.github.io/"
languageCode = "en-us"
title = "Pinnit One"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Guides"
    url = "/guides/"
    weight = 1
  [[menu.nav]]
    name = "Pricing"
    url = "/pricing/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.company]]
    name = 'About'
    url = "/about/"
    weight = 1
  [[menu.product]]
    name = 'Guides'
    url = "/guides/"
    weight = 1
  [[menu.product]]
    name = 'Pricing'
    url = "/pricing/"
    weight = 2
  [[menu.product]]
    name = 'What we log?'
    url = "/logging/"
    weight = 3
